server:
  port: 3344
spring:
  application:
    name: microservicecloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/github-zwh/microservicecloud-config.git

