server:
  port: 9527

spring:
  application:
    name: microservicecloud-gateway-zuul

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com #自定义hystrix相关服务的名称信息
    prefer-ip-address: true  #访问路径可以显示ip地址
info:
  app.name: zwh-microservicecloud
  company.name: www.zwh.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: microservicecloud-dept #忽略默认的路由规则
  prefix: /zwh
